#!/usr/bin/env python

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# this is the wrapper shell script to invoke the Slider.py script in the same folder
# Usage: slider <action> <commands>

import os
import sys
import subprocess

pyExecPath = None

if os.path.isfile('/usr/bin/python2.7') and (pyExecPath is None):
  pyExecPath = '/usr/bin/python2.7'
if os.path.isfile('/usr/bin/python2.6') and (pyExecPath is None):
  pyExecPath = '/usr/bin/python2.6'
if os.path.isfile('/usr/bin/python') and (pyExecPath is None):
  pyExecPath = '/usr/bin/python'
if pyExecPath is None:
  pyExecPath = 'python'

ON_POSIX = 'posix' in sys.builtin_module_names
currDir = os.path.dirname(os.path.realpath(__file__))
args = sys.argv[1:]
cmd = [pyExecPath + " " + currDir + "/slider.py"]
cmd.extend(args)
finalCmd = " ".join(cmd)

result = subprocess.call(finalCmd, shell=True)
sys.exit(result)
